"""crear tablas iniciales: usuarios, partidas, participaciones, eventos, ranking

Revision ID: db7e5454f22c
Revises: 
Create Date: 2026-10-05 18:38:22.211170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7e5454f22c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('esperando', 'en_curso', 'finalizada', name='estadopartida'), nullable=True),
    sa.Column('escenario', sa.String(length=50), nullable=True),
    sa.Column('tiempo_limite_segundos', sa.Integer(), nullable=True),
    sa.Column('puntuacion_objetivo', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('correo_verificado', sa.Boolean(), nullable=True),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('nombre_usuario')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('puntaje_final', sa.Integer(), nullable=True),
    sa.Column('posicion_final', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jugador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranking_global',
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('puntos_totales', sa.Integer(), nullable=True),
    sa.Column('victorias', sa.Integer(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jugador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('jugador_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ranking_global')
    op.drop_table('participaciones')
    op.drop_table('eventos')
    op.drop_table('usuarios')
    op.drop_table('partidas')
    # ### end Alembic commands ###
